### ISSUE TITLE
exporting got reverse (minecraft story mode season 2)

### ISSUE THREAD

**Issue by NoelGIJR** [LucasSaragosa/TelltaleInspector#1]
**ORIGINAL**

![Screenshot 2023-11-21 191515](https://github.com/LucasSaragosa/TelltaleInspector/assets/115152799/a261da92-7156-4521-b640-530da617bf46)

**_EXPORTED_**

![Screenshot 2023-11-21 191417](https://github.com/LucasSaragosa/TelltaleInspector/assets/115152799/a0144877-83f0-40ea-a5dc-abc8f3d44864)

so yeah i was trying to edit .prop files minecraft story mode season 2 to do model swap easily (or maybe season 1 can happened too welp i didnt try it but pretty sure)
the .prop properties got reverse from _skeleton face to symbol_ and when i try the games is like not working :(((

**Comment by LucasSaragosa** [comment]
your question isnt very helpful.
Skeleton Face in the second prop does not exist or you have not scrolled down, they look like two completely different props

**Comment by LucasSaragosa** [comment]
i opened the prop. you havent scrolled down in the properties list. they are all there

**Comment by LucasSaragosa** [comment]
thats not a problem with the tool, your modding is not telling the game the correct thing

**Comment by LucasSaragosa** [comment]
yea its not the tool its the game.
did u read the info at the beginning of the tool? it said not to use it with different games

**Comment by LucasSaragosa** [comment]
question is not related to the tool but due to a lack of modding experience
